name: Create Custom Zip

on:
  push:
    branches:
      - main

jobs:
  create_zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Prepare Files
      run: |
        # Creează un folder temporar pentru fișierele dorite
        mkdir -p temp/lib
        # Mută fișierul checkplayer.luac în folderul temporar
        cp checkplayer.luac temp/
        # Mută folderul lib în folderul temporar
        cp -r lib temp/lib

    - name: Create Custom Zip
      run: |
        # Creează arhiva zip cu fișierele dorite din folderul temporar
        zip -r checkplayer.zip temp/* -i 'temp/checkplayer.luac' 'temp/lib/*'

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: checkplayer
        path: checkplayer.zip
