name: Notify Discord on Changelog Update

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit SHA
        id: get-sha
        run: echo "CURRENT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Fetch previous commit
        id: fetch-prev
        run: |
          git fetch --depth=2
          echo "PREVIOUS_SHA=$(git rev-parse HEAD^)" >> $GITHUB_ENV

      - name: Get changed files
        id: get_changes
        run: |
          git diff --name-only ${{ env.PREVIOUS_SHA }} ${{ env.CURRENT_SHA }} > changes.txt
          cat changes.txt
          CHANGED_FILES=$(cat changes.txt)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Check if CHANGELOG.md was updated
        id: check_changelog
        run: |
          if echo "${{ env.CHANGED_FILES }}" | grep -q 'CHANGELOG.md'; then
            echo "CHANGELOG.md was updated" >> $GITHUB_ENV
          else
            echo "CHANGELOG.md was not updated" >> $GITHUB_ENV
          fi

      - name: Send update to Discord
        if: ${{ env.CHANGED_FILES == 'CHANGELOG.md' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"CHANGELOG.md was updated!\"}" $DISCORD_WEBHOOK
