name: Changelog to Discord

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Changelog to Discord
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_MESSAGE: "New release: ${{ github.event.release.tag_name }}\n${{ github.event.release.body }}"