name: Notify Discord on Changelog Update

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit SHA
        id: get-sha
        run: echo "CURRENT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Fetch previous commit
        id: fetch-prev
        run: |
          git fetch --depth=2
          echo "PREVIOUS_SHA=$(git rev-parse HEAD^)" >> $GITHUB_ENV

      - name: Get changed files
        id: get_changes
        run: |
          git diff --name-only ${{ env.PREVIOUS_SHA }} ${{ env.CURRENT_SHA }} > changes.txt
          cat changes.txt
          CHANGED_FILES=$(cat changes.txt)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Check if CHANGELOG.md was updated
        id: check_changelog
        run: |
          if echo "${{ env.CHANGED_FILES }}" | grep -q 'CHANGELOG.md'; then
            echo "CHANGELOG_MD_UPDATED=true" >> $GITHUB_ENV
          else
            echo "CHANGELOG_MD_UPDATED=false" >> $GITHUB_ENV
          fi

      - name: Send update to Discord
        if: ${{ env.CHANGELOG_MD_UPDATED == 'true' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Read the content of CHANGELOG.md
          CHANGES_CONTENT=$(cat CHANGELOG.md)
          
          # Create a JSON payload with the content
          PAYLOAD=$(jq -n --arg content "CHANGELOG.md was updated!\n\n\`\`\`\n$CHANGES_CONTENT\n\`\`\`" '{content: $content}')

          # Send the payload to Discord
          curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" $DISCORD_WEBHOOK
