name: Notify Discord on Changelog Update

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: get_changes
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD
          # List changed files and save them in an output
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Check if CHANGELOG.md was updated
        id: check_changelog
        run: |
          if echo "${{ env.CHANGED_FILES }}" | grep -q 'CHANGELOG.md'; then
            echo "CHANGELOG.md was updated" >> $GITHUB_ENV
          else
            echo "CHANGELOG.md was not updated" >> $GITHUB_ENV
          fi

      - name: Send update to Discord
        if: ${{ env.CHANGELOG_MDX_UPDATED == 'CHANGELOG.md was updated' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"CHANGELOG.md was updated!\"}" $DISCORD_WEBHOOK
